# Generated by Django 3.2.5 on 2021-07-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_alter_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\carl_\\PythonProjects\\webshop\\media/<django.db.models.fields.CharField>'),
        ),
    ]
