# Generated by Django 3.2.5 on 2021-07-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_alter_item_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemrelationship',
            old_name='created',
            new_name='buydate',
        ),
    ]
